### ISSUE TITLE
No effect

### ISSUE THREAD

**Issue by qadws007** [cazzwastaken/crashed#7]
![微信图片_20221109170624](https://user-images.githubusercontent.com/36926966/200787686-15288084-e249-422a-99f9-88e462bd614a.jpg)
After inject, this interface is displayed. No other effect.

**Comment by cazzwastaken** [comment]
Unfortunately the current version has been stripped of the ESP because I've been updating the SDK. If you have a little bit of C++ knowledge take a look at [visuals](https://github.com/cazzwastaken/crashed/blob/master/src/core/hacks/visuals.cpp) all the code has been commented out. You could rebuild it in a few minutes.

Anyway I'll implement the ESP in master soon. Cheers.
